### PR TITLE
Added Hybrid Support for Old & New Roblox Topbar

### PR DESCRIPTION
**Pull request by iamEvanYT**
Roblox is experimenting a [new, more compact Topbar](https://devforum.roblox.com/t/icymi-experience-controls-test-starting-november-20/2702634), which doesn't match the current style.
In this PR, I changed the code to use [GuiService.TopbarInset](https://create.roblox.com/docs/en-us/reference/engine/classes/GuiService#TopbarInset) property to determine if the user is using the old or the new one (>36 pixels).
If it is the new one, it would switch the theme to the new style.

@1ForeverHD, please check this PR.

image

### CODE REVIEW

**Comment by fgclue** [comment]
Hope this gets into main, UIShelf has never worked for me.

**Comment by iamEvanYT** [comment]
> Hope this gets into main, UIShelf has never worked for me.

Hello, if you want to, you can use my [fork](https://github.com/iamEvanYT/TopbarPlus/releases/tag/v.2.9.3) for now.
It supports both topbars!

**Comment by fgclue** [comment]
Thanks!

**Comment by 1ForeverHD** [comment]
Many thanks for this Evan! I'll be using some of this code for the re-write.

**Pull request merged**
